if localStorage.getItem 'Translate'
  window.TRANSLATE = localStorage.getItem 'Translate'
else
  window.TRANSLATE = false

window.SPANISH =
  translate: 'English'
  newTeam: 'Nuevo Equipo'
  startMatch: 'Iniciar Partido'
  playerNumber: 'Numero Jugador'
  playerName: 'Nombre Jugador'
  add: 'Agregar'
  done: 'Completado'
  back: 'Atras'
  duplicated: 'Jugador Duplicado'
  newMember: 'Nuevo Miembro'
  wrongData: 'Datos Incorrectos'
  enterName: 'Ingresa Nombre Manager'
  errorTeam: 'Error Equipo Contrario'
  spikePoint: 'Punto Ataque'
  spikeNormal: 'Ataque sin Punto'
  spikeError: 'Error Ataque'
  blockPoint: 'Punto Bloque'
  blockNormal: 'Bloque sin Punto'
  blockError: 'Error Bloque'
  servicePoint: 'Punto Servicio'
  serviceNormal: 'Servicio sin Punto'
  serviceError: 'Error Servicio'
  setPerfect: 'Colocada Perfecta'
  setNormal: 'Colocada Regular'
  setError: 'Error Colocada'
  passPerfect: 'Pase Perfecto'
  passNormal: 'Pase Regular'
  passError: 'Error Pase'
  digPerfect: 'Defensa Perfecta'
  digNormal: 'Defensa Regular'
  digError: 'Error Defensa'
  total: 'Totales'
  createNewTeam: 'Quieres Reemplazar tu equipo?'
  players: 'Jugadores'

window.ENGLISH =
  translate: 'Espanol'
  newTeam: 'New Team'
  startMatch: 'Start Match'
  playerNumber: 'Player Number'
  playerName: 'Player Name'
  add: 'Add'
  done: 'Done'
  back: 'Back'
  newMember: 'New Member'
  duplicated: 'Duplicated Player'
  wrongData: 'Wrong Player Data'
  enterName: 'Enter Manager Name'
  errorTeam: 'Error Opposing Team'
  spikePoint: 'Spike Point'
  spikeNormal: 'Spike No Point'
  spikeError: 'Spike Error'
  blockPoint: 'Block Point'
  blockNormal: 'Block No Point'
  blockError: 'Block Error'
  servicePoint: 'Service Point'
  serviceNormal: 'Service No Point'
  serviceError: 'Service Error'
  setPerfect: 'Perfect Set'
  setNormal: 'Regular Set'
  setError: 'Set Error'
  passPerfect: 'Perfect Pass'
  passNormal: 'Regular Pass'
  passError: 'Error Pass'
  digPerfect: 'Perfect Dig'
  digNormal: 'Regular Dig'
  digError: 'Error Dig'
  total: 'Totals'
  createNewTeam: 'Do you want to replace your team?'
  players: 'Players'
